### ISSUE TITLE
Todo for first version

### ISSUE THREAD

**Issue by Koenkk** [Koenkk/xiaomi-zb2mqtt#2]
- [x] Wiki: Getting started
- [x] Wiki: Running the gateway
- [x] Wiki: Supported devices
- [x] Wiki: (Bonus) How to integrate with home assistant
- [x] More robust MQTT connect fail handling
- [x] Support basic range of devices
- [x] Improve stability
- [x] MQTT authentication
